name: Valgrind Test

on:
  push:
    branches:
      - main

jobs:
  valgrind:
    runs-on: ubuntu-latest
    steps:
    - name: Install Valgrind and LibC Debug Symbols
      run: |
        sudo apt update
        sudo apt install -y valgrind libc6-dbg
    - name: Install cargo-valgrind
      run: |
        cargo install cargo-valgrind
    - name: Run Valgrind
      run: |
        cargo valgrind test
